### ISSUE TITLE
[Question] Controlling rate of speed of voice over - regd.

### ISSUE THREAD

**Issue by harir5** [AccessLint/voiceover.js#4]
Hi Cameron,

I used your really amazing node module to run accessibility tests in our automation framework and one thing that i wanted to understand is if we could control the test to ensure that the screen reader output can be heard before it moves to the next target on screen. is this possible to specify programmatically please? one of the things i received as feedback was to wait until the screen reader reads the current phrase out on screen fully before moving to the next phrase/target and capture it in the video.

**Comment by ckundo** [comment]
that's good feedback @harir5, thanks! I'll look at making that configurable.

**Comment by harir5** [comment]
Thank you Cameron. i will also see if this can be done from my end as well ! Amazing tool btw ! :-)

**Comment by ckundo** [comment]
@harir5 please take a look at the PR... you can set a delay between navigation with that PR.

**Comment by harir5** [comment]
Thanks @ckundo  - will take a look at it

**Comment by harir5** [comment]
Hi @ckundo  - it worked ! thank you very much ! :-)

**Comment by ckundo** [comment]
published in `v0.5.0`
